### ISSUE TITLE
Swift 3.0 unavailable 

### ISSUE THREAD

**Issue by dmitriymolokov** [Igor-Palaguta/YoutubeEngine#1]
Hey, thank for your library.
I have a problem with installation pod on swift 3

Terminal shows 

```
Pre-downloading: `YoutubeEngine` from `https://github.com/Igor-Palaguta/YoutubeEngine.git`, branch `swift-3`
[!] Unable to find a specification for `ReactiveSwift` depended upon by `YoutubeEngine`
```

What I should do?

**Comment by Igor-Palaguta** [comment]
ReactiveSwift is not yet pushed to cocoapods public specs repository
try to add this to your Podfile:

```
pod 'ReactiveSwift', :git => 'https://github.com/ReactiveCocoa/ReactiveSwift.git'
```

You can copy it from Example's podfile https://github.com/Igor-Palaguta/YoutubeEngine/blob/swift-3/Example/Podfile

**Comment by dmitriymolokov** [comment]
It works! Thank you!

**Comment by Igor-Palaguta** [comment]
You are welcome
