### ISSUE TITLE
Channels snippets are nil

### ISSUE THREAD

**Issue by lucamegh** [Igor-Palaguta/YoutubeEngine#2]
let engine = …
let channelIds = ...
engine.channels(Channels.init(Channels.Filter.byIds(channelIds), parts: [.snippet]))

Channel's snippet is nil.

**Comment by Igor-Palaguta** [comment]
Hello @lucamegh ! Thank you for feedback

Please check how it works now, fixed in https://github.com/Igor-Palaguta/YoutubeEngine/commit/efc5486cec9ff3893a516519ce1259d2fdd1d807

**Comment by lucamegh** [comment]
Thank you. Your work is remarkable
