### ISSUE TITLE
Results not available even though video Id exists

### ISSUE THREAD

**Issue by darkandchoco** [Igor-Palaguta/YoutubeEngine#4]
When the youtube ID contains dashes "-", the search results return nothing even though the youtube video id exists.

Works correctly for youtubeIds without dashes

Example id: gL-WVjvzu34

If you go to youtube: https://www.youtube.com/watch?v=gL-WVjvzu34, the video exists

But when I search using:

        let engine = Engine(.key(YOUTUBE_API_KEY))
        let youtubeId: String = "gL-WVjvzu34"
        let limit = 5
     
        engine.logEnabled = false
        let request: Search = Search(.term(youtubeId, [.video: [.snippet, .contentDetails]]),
                                     limit: limit)
        engine.search(request).startWithResult {
            result in
        
            if let page = result.value {
                //page here has no results 
            }
        }

I get no results

**Comment by darkandchoco** [comment]
i just found out that the video won't be in the search result if the video is not publicly listed.

Can we have a search feature using the video id?

**Comment by Igor-Palaguta** [comment]
Hello @darkandchoco,

Thanks for feedback. You are using api for searching by term. Try mentioned below code to search by id

```
      engine
         .videos(Videos(.byIds(["gL-WVjvzu34"]),
                        parts: [.snippet, .contentDetails],
                        limit: 10))
         .startWithResult { result in
            print(result)
      }
```

**Comment by darkandchoco** [comment]
Thanks @Igor-Palaguta !! It works now!
